name: Build and Test

on:
  push:
    branches:
      - main
      - release
    tags:
      - 'v*'
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Install Coverlet
        run: dotnet tool install --global coverlet.console

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build

      - name: Run tests with coverage
        run: dotnet test -c Release --collect:"XPlat Code Coverage"

      # New steps to create a signal for v-tag pushes
      - name: Create v-tag signal file
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          mkdir -p ${{ github.workspace }}/publish-signal
          echo "Triggered by v-tag: ${{ github.ref }}" > ${{ github.workspace }}/publish-signal/is_v_tag_release.txt
      - name: Upload v-tag signal artifact
        if: startsWith(github.ref, 'refs/tags/v')
        uses: actions/upload-artifact@v4 # Use a current version like v4
        with:
          name: v-tag-signal-artifact
          path: ${{ github.workspace }}/publish-signal/is_v_tag_release.txt
          retention-days: 1 # Optional: keep artifact for a short period