name: Build and Test

on:
  push:
    branches: 
      - main
      - release
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Install Coverlet
        run: dotnet tool install --global coverlet.console

      - name: Restore
        run: dotnet restore DotDice/DotDice.csproj

      - name: Build 
        run: dotnet build DotDice/DotDice.csproj

      - name: Run tests with coverage
        run: dotnet test DotDiceTests/DotDiceTests.csproj
      
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5.4.0
        with:
          # Comma-separated list of folders to exclude from search.
          #exclude: # optional
          fail_ci_if_error: true
          files: ./coverage/coverage.cobertura.xml
