name: Build and Test

on:
  push:
    branches: 
      - main
      - release
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Install Coverlet
        run: dotnet tool install --global coverlet.console

      - name: Restore
        run: dotnet restore

      - name: Build 
        run: dotnet build

      - name: Run tests with coverage
        run: dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:CoverletOutput=./coverage/

      - name: Verify coverage report
        run: |
          if [ ! -f "./coverage/coverage.cobertura.xml" ]; then
            echo "Error: Coverage report not found!"
            echo `ls ./coverage`
            exit 1
          fi
