name: Publish to NuGet

on:
  workflow_run:
    workflows:
      - Build and Test # Replace with the exact name of your build-and-test workflow
    types:
      - completed

jobs:
 pack-and-publish:
   if: ${{ github.event.workflow_run.conclusion == 'success' && startsWith(github.ref, 'refs/tags/v') }}
   runs-on: ubuntu-latest
   steps:
     - name: Checkout repository
       uses: actions/checkout@v3
   
     - name: Pack
       run: dotnet pack ./DotDice/DotDice.csproj -c Release -o .

     - name: Push to NuGet
       run: dotnet nuget push *.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }}
